# Generated by Django 4.2.10 on 2024-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_appuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                ("likes", models.CharField(max_length=5)),
                ("shares", models.CharField(max_length=5)),
                ("comments", models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name="React",
        ),
    ]
